# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RGBtoTif
                                 A QGIS plugin
 RGBtoTif
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-11
        copyright            : (C) 2025 by vce
        email                : gvreddy718@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RGBtoTif class from file RGBtoTif.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RGBtoTif import RGBtoTif
    return RGBtoTif(iface)
