# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LidarConversion
                                 A QGIS plugin
 Conversion from pcap to las/laz as a QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-05
        copyright            : (C) 2025 by VCE
        email                : sirikasturi111@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LidarConversion class from file LidarConversion.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lidar_conversion import LidarConversion
    return LidarConversion(iface)
